# Generated by Django 3.0.5 on 2020-05-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='kaisetu',
            field=models.TextField(blank=True),
        ),
    ]
