# Generated by Django 3.0.5 on 2020-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0002_question_kaisetu'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mondai',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='seikai',
            field=models.TextField(blank=True),
        ),
    ]
